version: '3'
services:
  db:
    image: mysql
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - .db/data:/var/lib/mysql
      - .db/my.cnf:/etc/mysql/conf.d/my.cnf
      - .db/sql:/docker-entrypoint-initdb.d
  be:
    depends_on:
      - db
    build:
      context: be
  fe:
    build:
      context: fe
  rp:
    depends_on:
      - be
      - fe
    build:
      context: rp
    ports:
      - 8080:80
