import { AxiosProvider } from './_components/AxiosProvider';
import { ThemeProvider } from './_components/ThemeProvider';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <AxiosProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </AxiosProvider>
      </body>
    </html>
  );
}
